Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -327,7 +327,7 @@ jobs:
                 exit 1
               fi
       - run:
-          name: get backend url1
+          name: Backend smoke test
           command: |
             export BACKEND_IP=$(aws ec2 describe-instances \
               --query 'Reservations[*].Instances[*].PublicIpAddress' \
@@ -335,21 +335,92 @@ jobs:
               --output text)
             export API_URL="http://${BACKEND_IP}:3030/api/status"
             echo "API_URL = ${API_URL}"
-
-      - run:
-          name: Backend smoke test.
-          command: |
-            echo "API_URL = ${API_URL}"
             if curl "${API_URL}" | grep "ok"
             then
               exit 0
             else
               exit 1
             fi
+            
+  
+#      - run:
+#          name: Backend smoke test.
+#          command: |
+#            echo "API_URL = ${API_URL}"
+#            if curl "${API_URL}" | grep "ok"
+#            then
+#              exit 0
+#            else
+#              exit 1
+#            fi
               
       # Here's where you will add some code to rollback on failure 
       - revert-migrations
       - destroy-environment
+
+  cloudfront-update:
+      docker:
+      # Docker image here that supports AWS CLI.
+      - image: amazon/aws-cli
+      steps:
+      # Checkout code from git
+      - checkout
+      
+      - run:
+          name: Install dependencies
+          command: |
+              yum install -y tar gzip
+      - run:
+          name: Update cloudfront distribution
+          command: |
+              # your code here
+              aws cloudformation deploy \
+              --template-file .circleci/files/cloudfront.yml \
+              --region us-east-1 \
+              --stack-name "InitialStack" \
+              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+              --tags project=udapeople
+      # Here's where you will add some code to rollback on failure  
+      - destroy-environment         
+      - revert-migrations 
+
+  cleanup:
+      docker:
+      # Docker image here
+      - image: amazon/aws-cli
+      steps:
+      # Checkout code from git.
+      - checkout
+      - run:
+          name: Install dependencies
+          command: |
+              yum install -y tar gzip 
+      - run:
+          name: Get old stack workflow id
+          command: |
+              export OldWorkflowID=$(aws cloudformation \
+              list-exports --query "Exports[?Name==\`WorkflowID\`].Value" \
+              --no-paginate --output text)
+                  
+              echo OldWorkflowID- "${OldWorkflowID}"
+              echo CIRCLE_WORKFLOW_ID "${CIRCLE_WORKFLOW_ID:0:7}"
+              
+              #put the list of stacks here
+              export STACKS=($(aws cloudformation list-stacks --query "StackSummaries[*].StackName" \
+              --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
+                  
+              echo Stack names- "${STACKS[@]}"
+              
+              if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+              then
+                  echo "=============delete confirmed======================="              
+                  aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+                  aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+                  aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+              else
+                echo "==============cannot cleanup========================"
+                echo "no stacks found"
+              fi              
 
 
 workflows:
@@ -385,3 +456,7 @@ workflows:
             -  run-migrations
       - smoke-test:
           requires: [deploy-backend, deploy-frontend]
+      - cloudfront-update:
+          requires: [smoke-test]
+      #- cleanup:
+      #    requires: [cloudfront-update]
