Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -396,11 +396,31 @@ jobs:
     steps:
       # Checkout code from git
       - checkout
+  #    - run:
+#          name: Install dependencies
+#          command: |
+            # your code here
+#            sudo apt-get install curl python python-pip && pip install awscli
       - run:
-          name: Install dependencies
+          name: install awscli
+          command: |
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install    
+      - run:
+          name: Frontend smoke test.
           command: |
             # your code here
-            sudo apt-get install curl python python-pip && pip install awscli
+              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+              echo ${URL} 
+              if curl -s ${URL} | grep "Welcome"
+              then
+                # Change this to 0 after the job fails
+                exit 0
+              else
+                exit 1
+              fi
+
       - run:
           name: Get backend url
           command: |
@@ -429,19 +449,7 @@ jobs:
             else
               exit 1
             fi
-      - run:
-          name: Frontend smoke test.
-          command: |
-            # your code here
-              URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-              echo ${URL} 
-              if curl -s ${URL} | grep "Welcome"
-              then
-                # Change this to 0 after the job fails
-                exit 0
-              else
-                exit 1
-              fi
+
       # Here's where you will add some code to rollback on failure  
       - destroy-environment:
           id: ${CIRCLE_WORKFLOW_ID:0:7}
